### PR TITLE
Adds code indenting

### PR DESCRIPTION
**Pull request by ashfurrow**
Makes it easier to read, happy to change based on your preferences 🙇

### CODE REVIEW

**Comment by sunshinejr** [comment]
@ashfurrow we've made the same PR 😂😂😂

**Comment by sergdort** [comment]
And I made this changes too, but then noticed your Pr 😂

**Comment by sergdort** [comment]
I guess we can close it :)

**Comment by ashfurrow** [comment]
Ha, my mistake! 
-- 
Ash Furrow
https://ashfurrow.com/

**Pull request closed without merging**
